export const HOME_STATUS_CHANGE = 'APPLICATION::HOME_STATUS_CHANGE';
export const HOME_CVD = 'APPLICATION::HOME_CVD';
export const HOME_DIABETES = 'APPLICATION::HOME_DIABETES';
export const HOME_WOUNDCARE = 'APPLICATION::HOME_WOUNDCARE';
